### PR TITLE
fix: Clarify intended visibility

### PR DESCRIPTION
**Pull request by epage**

### CODE REVIEW

**Comment by ordian** [comment]
FWIW, I generally prefer pub items in private modules to `pub(crate)` everything, because the latter usually leads to (unnecessary) tight coupling of every module.

**Comment by epage** [comment]
> FWIW, I generally prefer pub items in private modules to pub(crate) everything, because the latter usually leads to (unnecessary) tight coupling of every module.

My reasons for this
- It is unclear what is intended to make it to the public API or not
- `pub` is viral, if a `pub` item references a non-`pub` type, that type must be made `pub`.  `CustomError` is one example of this.

I'm all game for making this more restrictive than `pub(crate)`, this was just a first pass.

**Comment by epage** [comment]
Oh, apparently this let us also reduce `TableKeyValue`s visibility

**Comment by ordian** [comment]
Makes sense!

**Pull request merged**
