### PR TITLE
Support dotted keys

### PR DESCRIPTION
**Pull request by ironyman**
* Changed struct Key to SimpleKey. Key is now a vector SimpleKeys.
* Changed key and key path parsing.
* Added for_dotted in struct Table to keep track of tables created for dotted keys.
* Work in progress. Especially insertion logic.
* Needs more tests.

### CODE REVIEW

**Comment by ordian** [comment]
Looks in the right direction. Let me know when this is ready.

**Comment by ironyman** [comment]
At first, upon parsing a dotted key, I tried to create a table for each simple key in the dotted key. But that made it difficult to to convert the AST back to string. That is, to print the dotted keys in the current table (at the current level in the AST), we'd have to descend into child tables (of the dotted key) until we hit the leaf node to get the full path of the dotted key. That's considerably messier than what we have now where we just walk the AST once and all information required to print the current table is in the current AST node of the table.
So I made the key of `Table.items: KeyValuePairs` into a vector 
```
pub(crate) type KeyValuePairs = LinkedHashMap<Vec<InternalString>, TableKeyValue>;
```
And dotted keys would not have a table for each non leaf simple key part, but it would be in the items table, like simple keys.

Unfortunately, this means `to_json` in the tests no longer just work. Given 
```
a.b.c = 1
```
we end up 
```
"a.b.c": {
...
}
```

To fix this we'd have to create objects for the dotted keys in `to_json` and I'd probably have to replace the iterators and adapters there with loops because it's messy and I can't think of any other way to do it. 

Thoughts?

**Comment by ordian** [comment]
@ironyman I don't think having a `HashMap<Vec<Key>, _>` is gonna fly. We want to be able to access the keys one by one, e.g. in the following toml
```toml
[dependencies.toml]
version = "0.5"

[dependencies.serde]
version = "1.0"
```
`doc["dependencies"]` should return a table and not simply fail. The same applies for dotted keys:
```toml
dependencies.toml = { version = "0.5" }
dependencies.serde = { version = "1.0" }
```
I think we don't store table headers (like `[dependencies.toml]`) in tables themselves, but still able to print it properly (see https://github.com/ordian/toml_edit/blob/b679b5e610b9a19f48fa0268f9174062e9c43962/src/display.rs#L80-L137).

**Comment by ironyman** [comment]
Closing this because I made a new branch

**Pull request closed without merging**
