### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by parasyte**
This documents additional breaking changes that I ran into when updating.

The breaking commit was https://github.com/ordian/toml_edit/pull/240/commits/84f32008ebb142f641d9e56a6ad936f41fb05dee

### CODE REVIEW

**Review by ordian — APPROVED** [review]

**Comment by parasyte** [comment]
It's technically `std::ops::Index` that changed. I just noticed `toml_edit` has its own `Index` trait, and this addition to changelog is a bit ambiguous.

**Comment by ordian** [comment]
The one that's exposed in the API: https://docs.rs/toml_edit/0.8.0/toml_edit/easy/value/trait.Index.html probably should be hidden as the one in `src/index.rs`.

**Comment by parasyte** [comment]
Thanks! That would be helpful, IMHO.

**Comment by epage** [comment]
Ah, sorry I lost track of that and didn't record it!  I figured it was the more expected behavior.

**Pull request merged**
