### PR TITLE
Add `From<Array>` and `From<InlineTable>` for `Value`

### PR DESCRIPTION
**Pull request by pwoolcoc**

### CODE REVIEW

**Comment by pwoolcoc** [comment]
hey, i was hoping to use this in a project but can't use a `git = ` dependency in a crates.io crate. Do you have any plans to release a 0.1.2 anytime soon?

**Comment by ordian** [comment]
@pwoolcoc I'll publish 0.1.2 hopefully in a week (need to upgrade to latest combine and improve the docs). Is that ok with you?

**Comment by ordian** [comment]
@pwoolcoc 0.1.2 is published.

**Comment by pwoolcoc** [comment]
@ordian wow, I'm a month late on this T_T

but thanks very much!

**Pull request merged**
